### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by ufechner7** [awebox/awebox#132]
On Ubuntu 22.04, the installation fails with:
```
ufechner@ufryzen:~/repos$ pip3 install awebox/
Defaulting to user installation because normal site-packages is not writeable
Processing ./awebox
  Preparing metadata (setup.py) ... done
Collecting Pillow==9.2.0
  Downloading Pillow-9.2.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 15.9 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement casadi==3.5.5 (from awebox) (from versions: 3.5.6rc2, 3.6.0, 3.6.1, 3.6.2, 3.6.3)
ERROR: No matching distribution found for casadi==3.5.5
ufechner@ufryzen:~/repos$ 

```

**Comment by pilotmm** [comment]
Same problem ... I tried to fix it by changing the required version of casadi to the lowest one available in the pip system.

I get this error:

```
(env_awebox) mike@pilotfedora~/work/DTU/conferences/AWEC_2024/research/AWEBOX/awebox/examples$ python ampyx_ap2_trajectory.py 
INFO:	
INFO:	++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO:	This is awebox, a modeling and optimization framework for multi-kite AWE systems.
INFO:	awebox is free software; you can redistribute it and/or modify it under the terms
INFO:	of the GNU Lesser General Public License as published by the Free Software
INFO:	Foundation license. More information can be found at http://github.com/awebox.
INFO:	++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO:	
INFO:	============================================================
INFO:	            Building trial "Ampyx_AP2" ...
INFO:	============================================================
INFO:	
INFO:	Building model...
Traceback (most recent call last):
  File "/home/mike/work/DTU/conferences/AWEC_2024/research/AWEBOX/awebox/examples/ampyx_ap2_trajectory.py", line 47, in <module>
    trial.build()
  File "/home/mike/work/DTU/conferences/AWEC_2024/research/AWEBOX/env_awebox/lib64/python3.11/site-packages/awebox/trial.py", line 106, in build
    self.__model.build(self.__options['model'], architecture)
  File "/home/mike/work/DTU/conferences/AWEC_2024/research/AWEBOX/env_awebox/lib64/python3.11/site-packages/awebox/mdl/model.py", line 60, in build
    self.__generate_system_dynamics(options)
  File "/home/mike/work/DTU/conferences/AWEC_2024/research/AWEBOX/env_awebox/lib64/python3.11/site-packages/awebox/mdl/model.py", line 102, in __generate_system_dynamics
    integral_scaling] = dyn.make_dynamics(options, self.__atmos, self.__wind, self.__parameters, self.__architecture)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/work/DTU/conferences/AWEC_2024/research/AWEBOX/env_awebox/lib64/python3.11/site-packages/awebox/mdl/dynamics.py", line 91, in make_dynamics
    lagr_dyn_cstr, outputs = lagr_dyn.get_dynamics(options, atmos, wind, architecture, system_variables, system_gc, parameters, outputs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/work/DTU/conferences/AWEC_2024/research/AWEBOX/env_awebox/lib64/python3.11/site-packages/awebox/mdl/lagr_dyn_dir/lagr_dyn.py", line 55, in get_dynamics
    f_nodes, outputs = forces_comp.generate_f_nodes(options, atmos, wind, system_variables['SI'], parameters, outputs,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/work/DTU/conferences/AWEC_2024/research/AWEBOX/env_awebox/lib64/python3.11/site-packages/awebox/mdl/lagr_dyn_dir/forces.py", line 59, in generate_f_nodes
    tether_drag_forces, outputs = generate_tether_drag_forces(options, variables_si, parameters, atmos, wind, outputs,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/work/DTU/conferences/AWEC_2024/research/AWEBOX/env_awebox/lib64/python3.11/site-packages/awebox/mdl/lagr_dyn_dir/forces.py", line 101, in generate_tether_drag_forces
    tether_cd_fun = tether_drag_coeff.get_tether_cd_fun(options, parameters)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/work/DTU/conferences/AWEC_2024/research/AWEBOX/env_awebox/lib64/python3.11/site-packages/awebox/mdl/aero/tether_dir/coefficients.py", line 55, in get_tether_cd_fun
    tether_cd_fun = cas.Function('tether_cd_fun', [reynolds], [drag_coeff])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/work/DTU/conferences/AWEC_2024/research/AWEBOX/env_awebox/lib64/python3.11/site-packages/casadi/casadi.py", line 23583, in __init__
    this = _casadi.new_Function(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error in Function::Function for 'tether_cd_fun' [SXFunction] at .../casadi/core/function.cpp:224:
.../casadi/core/function_internal.cpp:145: Error calling SXFunction::init for 'tether_cd_fun':
.../casadi/core/sx_function.cpp:476: tether_cd_fun::init: Initialization failed since variables [theta0_tether_cd] are free. These symbols occur in the output expressions but you forgot to declare these as inputs. Set option 'allow_free' to allow free variables.
```

**Comment by pilotmm** [comment]
See release notes here https://web.casadi.org/get/#notesTab-36

It appears that casadi has made some breaking changes to the function object ... but it also appears that an option 'allow_free' is added to help alleviate these issues

...

**Comment by pilotmm** [comment]
So I can confirm that the source of the error is located at the following location in the code

```
  File "/home/mike/work/DTU/conferences/AWEC_2024/research/AWEBOX/env_awebox/lib64/python3.11/site-packages/awebox/mdl/aero/tether_dir/coefficients.py", line 55, in get_tether_cd_fun
    tether_cd_fun = cas.Function('tether_cd_fun', [reynolds], [drag_coeff])
```

If I change that line of code to the following:

```
tether_cd_fun = cas.Function('tether_cd_fun', [reynolds], [drag_coeff], {"allow_free":True})
```

then the code will run past this point ... but it will fail at the next instance of the ```cas.Function( ... )``` call. So it seems that one can update the requirements for casadi then update some of the python calls to ```cas.Function()``` to overcome the breaking changes in casadi
