### ISSUE TITLE
mpc_closed_loop.py doesn't work

### ISSUE THREAD

**Issue by Laxnring** [awebox/awebox#38]
I'm currently working my way through the examples to try and understand the awebox toolbox.
However running mpc_close_loop.py with the default exceptions throws the following exception:

```

Traceback (most recent call last):
  File "mpc_closed_loop.py", line 63, in <module>
    closed_loop_sim = awe.sim.Simulation(trial, 'closed_loop', ts, options)
  File "/home/pico/awebox/awebox/sim.py", line 54, in __init__
    self.__build()
  File "/home/pico/awebox/awebox/sim.py", line 80, in __build
    self.__mpc = pmpc.Pmpc(self.__mpc_options, self.__ts, self.__trial)
  File "/home/pico/awebox/awebox/pmpc.py", line 84, in __init__
    self.__construct_solver()
  File "/home/pico/awebox/awebox/pmpc.py", line 145, in __construct_solver
    f = self.__generate_objective()
  File "/home/pico/awebox/awebox/pmpc.py", line 255, in __generate_objective
    f = ct.mtimes(ct.vertcat(*quad_weights).T, cost_map(*cost_args).T)/self.__N
  File "/home/pico/.local/lib/python3.8/site-packages/casadi/casadi.py", line 13444, in __call__
    ret = self.call(args)
  File "/home/pico/.local/lib/python3.8/site-packages/casadi/casadi.py", line 12324, in call
    return _casadi.Function_call(self, *args)
RuntimeError: .../casadi/core/function_internal.hpp:1257: Input 0 (i0) has mismatching shape. Got 21-by-20. Allowed dimensions, in general, are:
 - The input dimension N-by-M (here 18-by-5)
 - A scalar, i.e. 1-by-1
 - M-by-N if N=1 or M=1 (i.e. a transposed vector)
 - N-by-M1 if K*M1=M for some K (argument repeated horizontally)
 - N-by-P*M, indicating evaluation with multiple arguments (P must be a multiple of 1 for consistency with previous inputs)

```

Any idea about what's going on here? I apologize if my error is in any way obvious, I'm not very familiar with awebox or casadi.

**Comment by thilobro** [comment]
Sadly I cannot reproduce your error message. It looks like a casadi function is getting a vector input with the wrong shape. Which commit are you based on? Did you make any alterations to the example? Please post the entire output of the awebox, not just the error traceback so we can get a better idea of when this occurs. Thanks!

**Comment by Laxnring** [comment]
Sorry for the delay and thank you for the quick response
I'm based on the develop commit and no, I haven't changed anything in the code, just running it after I cloned it. It only happens on the mpc_closed_loop.py, so that's why I found it a bit odd. I installed the HSL solver as a precompiled binary and installed casadi with pip (version 3.5.5 - could it have something to do with it?).
Thanks!

Here's the complete output:
```
python3 mpc_closed_loop.py 
INFO:	
INFO:	++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO:	This is awebox, a modeling and optimization framework for multi-kite AWE systems.
INFO:	awebox is a free software; you can redistribute it and/or modify it under the terms
INFO:	of the GNU Lesser General Public License as published by the Free Software
INFO:	Foundation license. More information can be found at http://github.com/awebox.
INFO:	++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO:	
INFO:	
INFO:	Building trial (single_kite_lift_mode) ...
INFO:	
INFO:	Building model...
INFO:	generate atmosphere...
INFO:	generate wind...
INFO:	generate system dynamics...
INFO:	generate variable bounds...
INFO:	generate parameter bounds...
INFO:	generate constraints..
INFO:	Model built.
INFO:	Model construction time: 0.2s
INFO:	
INFO:	Building formulation...
INFO:	generate parameters...
INFO:	generate variables...
INFO:	generate variable bounds...
INFO:	generate parameter bounds...
INFO:	generate constraints..
INFO:	generate outputs...
INFO:	Formulation built.
INFO:	Formulation construction time: 0.0s
INFO:	
INFO:	Building NLP...
INFO:	discretize problem... 
INFO:	generate variable bounds...
INFO:	generate objective... 
INFO:	NLP built.
INFO:	NLP construction time: 15.4s
INFO:	
INFO:	Building optimization...
INFO:	initialize callback...
INFO:	generate solvers...
INFO:	Optimization built.
INFO:	Optimization construction time: 2m51.1s
INFO:	
INFO:	Trial (single_kite_lift_mode) built.
INFO:	Trial construction time: 2m6.8s
INFO:	
INFO:	Optimizing trial (single_kite_lift_mode) ...
INFO:	
INFO:	Solving optimization...
INFO:	define homotopy update schedule...
INFO:	define args...
INFO:	build si initial guess...
WARNING:	proposed initial radius implies a cone angle above the maximum value. radius will be clipped to 86.82408883346517m.
INFO:	generate tracking reference...
INFO:	generate OCP parameter values...
INFO:	solve with homotopy procedure...
INFO:	
INFO:	################################################################################
INFO:	Initial solution...
INFO:	
INFO:	
INFO:	ERROR: Solver FAILED, not moving on to next step...
INFO:	solver return status..........: Invalid_Option                
INFO:	number of iterations..........: 189894632                     
INFO:	
INFO:	################################################################################
INFO:	
INFO:	process the solution...
INFO:	
INFO:	WARNING: Optimization of Trial (single_kite_lift_mode) failed.
WARNING:	energy balance for node 1 of trial single_kite_lift_mode not consistent. 9.88478896759263 > 0.02
WARNING:	energy balance for node total of trial single_kite_lift_mode not consistent. 9.88478896759263 > 0.02
WARNING:	#################################################
WARNING:	QUALITY CHECK results for single_kite_lift_mode:
WARNING:	8 of 11 tests passed.
WARNING:	3 tests failed. Solution might be numerically unsound.
WARNING:	For more information, use trial.quality.print_results()
WARNING:	#################################################
INFO:	
INFO:	generate dae object
INFO:	Creating a tracking periodic MPC controller with horizon length 10...
INFO:	Based on direct collocation with radau polynomials of order 4.
INFO:	Building MPC trial...
INFO:	Building model...
INFO:	generate atmosphere...
INFO:	generate wind...
INFO:	generate system dynamics...
INFO:	generate variable bounds...
INFO:	generate parameter bounds...
INFO:	generate constraints..
INFO:	Model built.
INFO:	Model construction time: 0.2s
INFO:	
INFO:	Building formulation...
INFO:	generate parameters...
INFO:	generate variables...
INFO:	generate variable bounds...
INFO:	generate parameter bounds...
INFO:	generate constraints..
INFO:	Introducing initial constraint...
INFO:	generate outputs...
INFO:	Formulation built.
INFO:	Formulation construction time: 0.0s
INFO:	
INFO:	Building NLP...
INFO:	discretize problem... 
INFO:	generate variable bounds...
INFO:	generate objective... 
INFO:	NLP built.
INFO:	NLP construction time: 2.1s
INFO:	
INFO:	Constructing MPC solver object...
INFO:	Generate MPC tracking objective...
Traceback (most recent call last):
  File "mpc_closed_loop.py", line 63, in <module>
    closed_loop_sim = awe.sim.Simulation(trial, 'closed_loop', ts, options)
  File "/home/pico/awebox/awebox/sim.py", line 54, in __init__
    self.__build()
  File "/home/pico/awebox/awebox/sim.py", line 80, in __build
    self.__mpc = pmpc.Pmpc(self.__mpc_options, self.__ts, self.__trial)
  File "/home/pico/awebox/awebox/pmpc.py", line 84, in __init__
    self.__construct_solver()
  File "/home/pico/awebox/awebox/pmpc.py", line 145, in __construct_solver
    f = self.__generate_objective()
  File "/home/pico/awebox/awebox/pmpc.py", line 255, in __generate_objective
    f = ct.mtimes(ct.vertcat(*quad_weights).T, cost_map(*cost_args).T)/self.__N
  File "/home/pico/.local/lib/python3.8/site-packages/casadi/casadi.py", line 13444, in __call__
    ret = self.call(args)
  File "/home/pico/.local/lib/python3.8/site-packages/casadi/casadi.py", line 12324, in call
    return _casadi.Function_call(self, *args)
RuntimeError: .../casadi/core/function_internal.hpp:1257: Input 0 (i0) has mismatching shape. Got 21-by-40. Allowed dimensions, in general, are:
 - The input dimension N-by-M (here 18-by-10)
 - A scalar, i.e. 1-by-1
 - M-by-N if N=1 or M=1 (i.e. a transposed vector)
 - N-by-M1 if K*M1=M for some K (argument repeated horizontally)
 - N-by-P*M, indicating evaluation with multiple arguments (P must be a multiple of 1 for consistency with previous inputs)


```

**Comment by thilobro** [comment]
So far, we only support casadi 3.4.5 in the awebox (see readme). So maybe you could try if the example runs with that version for you. I'm not sure how a new casadi version can cause a matrix dimension bug, but that would be my first guess. Also maybe @jdeschut can help you out, he implemented the example if I remember correctly

**Comment by jdeschut** [comment]
Hi @Laxnring ,

cool that you are looking into the `awebox`! Out of interest, what is your main interest in the software package?

There has been some code refactoring (particularly in the OCP objective formulation) in previous weeks/months that seems to have broken the MPC functionality -- which was working previously -- independent of CasADi version. I will have a look in the near future. In the mean time, the main contribution of the software package is offline trajectory optimization, so there should still be enough to explore.

Also, the output

```
INFO:	Optimizing trial (single_kite_lift_mode) ...
INFO:	
INFO:	Solving optimization...
INFO:	define homotopy update schedule...
INFO:	define args...
INFO:	build si initial guess...
WARNING:	proposed initial radius implies a cone angle above the maximum value. radius will be clipped to 86.82408883346517m.
INFO:	generate tracking reference...
INFO:	generate OCP parameter values...
INFO:	solve with homotopy procedure...
INFO:	
INFO:	################################################################################
INFO:	Initial solution...
INFO:	
INFO:	
INFO:	ERROR: Solver FAILED, not moving on to next step...
INFO:	solver return status..........: Invalid_Option                
INFO:	number of iterations..........: 189894632                     
INFO:	
INFO:	################################################################################
INFO:	
INFO:	process the solution...
INFO:	
INFO:	WARNING: Optimization of Trial (single_kite_lift_mode) failed
```
suggests that IPOPT does not find the HSL solver MA57, and the offline optimization failed before even getting to the MPC part. You can check if the problem is with the HSL solver by changing the linear solver to MUMPS with 
```
options['solver']['linear_solver'] = 'mumps'
```
In this case, the error should disappear. For small and simple problems, MUMPS works fine as well.

**Comment by Laxnring** [comment]
Thank you very much for your answer! 
I'm currently working with the [UPWind](http://www.upwind.pt/) at the University of Porto and we are trying to implement our own AWE system. We were looking at the state-of-the-art in terms of simulators to develop our own MPC MATLAB based solution and came across your project. That's the reason I was trying out your MPC example.

I will try and clone one of your earlier versions and see if it works. 

And thank you very much for the suggestion!

**Comment by jdeschut** [comment]
Hi @Laxnring ! Sorry for the late answer. The example is fixed now. Keep in mind that the idea here is to create a robust MPC solver (based on IPOPT) for explorative offline simulations, so it's pretty slow and some of the technical details are dealt with rudimentarily.

If you are interested in MPC for AWE, you might find this software + paper interesting as well: https://github.com/jdeschut/tunempc/blob/master/docs/tunempc_paper.pdf .

Good luck with your research and let us know if we can assist in using `awebox` in any way!
